<?php

namespace AppBundle\Repository;

use AppBundle\Entity\City;
use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{
    /**
     * @param $city
     * @return array
     */
    public function findLike($city)
    {
        $cities = [];
        $results = $this->createQueryBuilder('q')
            ->where('q.name LIKE :city')
            ->setParameter('city', $city."%")
            ->getQuery()->getResult();

        /** @var City $result */
        foreach ($results as $result) {
            $cities[] = ["id" => (string)$result->getId(), "text" => $result->__toString()];
        }

        return $cities;
    }
}
