<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;

/**
 * TravelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravelRepository extends EntityRepository
{
    /**
     * @param $sort
     * @param $order
     * @return DoctrineORMAdapter
     */
    public function paginator($sort, $order)
    {
        $queryBuilder = $this->createQueryBuilder('q');
        if ($sort == "category") {
            $queryBuilder->leftJoin("q.interests", "interests")->orderBy("interests.name", $order);
        }else {
            $queryBuilder = $this->createQueryBuilder('q')->orderBy("q.$sort", $order);
        }

        return $adapter = new DoctrineORMAdapter($queryBuilder->getQuery());
    }
}
