# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  admin.menu_listener:
        class: AdminBundle\EventListener\ListListener
        tags:
            - { name: kernel.event_listener, event:theme.sidebar_setup_menu, method:onSetupMenu }

  admin.travel:
        class: AppBundle\Admin\TravelAdmin
        arguments: [~, AppBundle\Entity\Travel, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Voyage, group: "Default" }
  admin.image:
        class: AppBundle\Admin\ImageAdmin
        arguments: [~, AppBundle\Entity\Image, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Image, group: "Default" }