# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

      #Event Listener
  app.doctrine_projects_listener:
      class: AppBundle\EventListener\UploadListener
      arguments: ["%upload_directory%"]
      tags:
          - { name: doctrine.event_listener, event: prePersist }
          - { name: doctrine.event_listener, event: preUpdate }
          - { name: doctrine.event_listener, event: postLoad }

  app.form.registration:
      class: UserBundle\Form\RegistrationType
      tags:
          - { name: form.type, alias: app_user_registration }

  admin.travel:
        class: AppBundle\Admin\TravelAdmin
        arguments: [~, AppBundle\Entity\Travel, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Voyage, group: "Default" }
  admin.image:
        class: AppBundle\Admin\ImageAdmin
        arguments: [~, AppBundle\Entity\Image, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Image, group: "Default" }

  app.twig_extension:
          class: AppBundle\Twig\Extension\ImageExtension
          public: false
          arguments: ["%web_dir%"]
          tags:
              - { name: twig.extension }
  app.paypal:
          class: AppBundle\Utils\Paypal
          arguments: ["@service_container"]

  app.gmap_coordinates:
          class: AppBundle\Utils\GMapCoordinates